
name: space-debris-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.3.1
  - numpy=1.24.3
  - pip:
    - azureml-defaults>=1.38.0
    - inference-schema[numpy-support]==1.3.0
    - requests==2.31.0
    - numpy==1.24.3
